# Generated by Django 2.1.5 on 2020-07-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitacion',
            name='cliente',
        ),
        migrations.AddField(
            model_name='cliente',
            name='habitacion',
            field=models.ManyToManyField(to='hotel.Habitacion'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='tipo',
            field=models.CharField(max_length=10),
        ),
    ]
