# Generated by Django 2.1.5 on 2020-07-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_auto_20200723_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='tipo',
            field=models.CharField(choices=[('MATRIMONIALES', 'Matrimoniales'), ('FAMILIARES', 'Familiares'), ('COMPARTIDAS', 'Compartidas'), ('SUITE', 'Suite')], default='COMPARTIDAS', max_length=10),
        ),
    ]
