# Generated by Django 2.1.5 on 2020-07-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_auto_20200726_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='tipo',
            field=models.CharField(choices=[('SENCILLAS', 'Sencillas'), ('DOBLES', 'Dobles'), ('MATRIMONIALES', 'Matrimoniales'), ('SUITE', 'Suite')], default='SENCILLAS', max_length=10),
        ),
    ]
