# Generated by Django 2.1.5 on 2020-08-02 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_auto_20200726_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitacion',
            name='cliente',
        ),
        migrations.AddField(
            model_name='cliente',
            name='habitacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hotel.Habitacion'),
            preserve_default=False,
        ),
    ]
