# Generated by Django 2.1.5 on 2020-08-12 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_auto_20200812_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitacion',
            name='mantenimineto',
        ),
    ]
