# Generated by Django 2.1.5 on 2020-08-12 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_remove_habitacion_mantenimineto'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='mantenimiento',
            field=models.BooleanField(default=False),
        ),
    ]
