# Generated by Django 2.1.5 on 2020-08-12 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_habitacion_descripcion'),
        ('hotel', '0011_habitacion_descripcion'),
    ]

    operations = [
    ]
